import org.junit.jupiter.api.Test
import kotlin.test.assertEquals


object Test_day8 {
    @Test
    fun star1(): Unit {
        val data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
        assertEquals(14, Day8.star1(data))
    }

    @Test
    fun start2_simple() {
        val data = """T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
.........."""
        assertEquals(9, Day8.star2(data))
    }


    @Test
    fun star2() {
        val data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
        assertEquals(34, Day8.star2(data))
    }
}


